linters:
  disable-all: true
  enable:
    - errcheck
    - godot
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - testifylint
    - testpackage
    - typecheck
    - unused
    - whitespace
